# Generated by Django 3.2.8 on 2021-10-10 07:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(blank=True, max_length=100)),
                ('friends', models.PositiveIntegerField(default=0)),
                ('picture', models.ImageField(blank=True, null=True, upload_to='users/pictures')),
                ('sex', models.CharField(choices=[('H', 'Hombre'), ('M', 'Mujer')], default='H', max_length=2)),
                ('relation', models.CharField(choices=[('R', 'En una relación'), ('N', 'Solter@'), ('D', 'Es complicado'), ('V', 'Viud@')], default='N', max_length=2)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
